[
  {
    id: 1,
    bookImage: "/assets/Books/Asset4.png",
    authorName: "Rudi Jennings",
    description:
      "Rudi Michael Jennings spent the majority of his childhood growing up in the Norfolk countryside...",
    moreInfo: "+ MORE ABOUT RUDI JENNINGS",
    bookTitle: "THE LAST MYON",
    fullDescription:
      "The Last Myon is a story of fantasy adventure, revenge and an individual's total unwillingness to submit or to fail, battling against overwhelming natural elements and a group of hardened sadistic creatures who will stop at nothing to succeed in his capture and slavery. In an everlasting winter world, Ackrehm, the last of his Myon kind, must fight for his life, sustaining multiple injuries along the way and still demonstrating he truly is a force to be reckoned with. Struggling with exhaustion, both mentally and physically, will he manage to overcome, or will he fight or flee? One thing is for certain, The Last Myon will keep you hooked until the very end, bonding with characters and excitedly reading on with an obsession to find out what happens next, promoting an ethos to take away of never give up, never surrender.",
    isbn: "9781848979345",
    publishedDate: "30/11/2017",
    pages: 147,
    wordsCount: 45648,
    size: "205x140mm",
    imprint: "Olympia Publishers",
    bookGenre: "Fiction",
  },
  {
    id: 2,
    bookImage: "/assets/Books/Asset5.png",
    authorName: "Jane Doe",
    description:
      "An insight into the world of fiction by Jane Doe, showcasing her brilliant narrative skills.",
    moreInfo: "+ MORE ABOUT JANE DOE",
    bookTitle: "Worlds Beyond",
    fullDescription:
      "Worlds Beyond is an exploration of alternate realities and the human spirit's resilience in the face of adversity. Jane Doe's storytelling weaves intricate plots and memorable characters, making it a compelling read from start to finish.",
    isbn: "9781234567891",
    publishedDate: "10/10/2020",
    pages: 300,
    wordsCount: 85000,
    size: "210x150mm",
    imprint: "Future Worlds Press",
    bookGenre: "Fiction",
  },
  {
    id: 3,
    bookImage: "/assets/Books/Asset6.png",
    authorName: "John Smith",
    description:
      "John Smith's debut novel explores complex themes of identity and belonging in a rapidly changing world.",
    moreInfo: "+ MORE ABOUT JOHN SMITH",
    bookTitle: "Echoes of the Past",
    fullDescription:
      "Echoes of the Past delves into the intertwined lives of its characters, uncovering secrets and revelations that challenge their perceptions of reality and self. John Smith crafts a narrative that is both thought-provoking and emotionally engaging.",
    isbn: "9781122334455",
    publishedDate: "01/05/2019",
    pages: 220,
    wordsCount: 65000,
    size: "200x130mm",
    imprint: "Heritage Publishers",
    bookGenre: "Fiction",
  },
  {
    id: 4,
    bookImage: "/assets/Books/Asset2.png",
    authorName: "Emily Zhang",
    description:
      "A mesmerizing collection of essays from Emily Zhang, reflecting on contemporary issues with depth and sensitivity.",
    moreInfo: "+ MORE ABOUT EMILY ZHANG",
    bookTitle: "Reflections in an Age",
    fullDescription:
      "Reflections in an Age is a collection of essays that tackle modern societal issues with a keen eye and thoughtful prose. Emily Zhang's writing is both introspective and outward-looking, making for a deeply impactful read.",
    isbn: "9780987654321",
    publishedDate: "15/08/2021",
    pages: 180,
    wordsCount: 50000,
    size: "215x135mm",
    imprint: "Modern Times Press",
    bookGenre: "Non-Fiction",
  },
  {
    id: 5,
    bookImage: "/assets/Books/Asset3.png",
    authorName: "Carlos Ramirez",
    description:
      "Carlos Ramirez returns with a thrilling sequel to his bestselling novel, weaving suspense and mystery with expert precision.",
    moreInfo: "+ MORE ABOUT CARLOS RAMIREZ",
    bookTitle: "The Maze Shadows",
    fullDescription:
      "The Maze Shadows is a gripping sequel that takes readers deeper into a world of intrigue and danger. Carlos Ramirez masterfully balances suspense with character development, creating a narrative that keeps readers on the edge of their seats.",
    isbn: "9781472583690",
    publishedDate: "12/12/2022",
    pages: 350,
    wordsCount: 90000,
    size: "220x145mm",
    imprint: "Thrill Ride Publishing",
    bookGenre: "Thriller",
  },
  {
    id: 6,
    bookImage: "/assets/Books/Asset4.png",
    authorName: "Alice Walker",
    description:
      "Alice Walker's latest novel captures the essence of human emotions in the face of societal challenges.",
    moreInfo: "+ MORE ABOUT ALICE WALKER",
    bookTitle: "The Silent Echo",
    fullDescription:
      "The Silent Echo is a poignant exploration of love, loss, and resilience. Alice Walker's lyrical prose and deeply human characters make this a novel that resonates on multiple levels.",
    isbn: "9780456789101",
    publishedDate: "25/07/2018",
    pages: 280,
    wordsCount: 72000,
    size: "210x140mm",
    imprint: "Echo Press",
    bookGenre: "Fiction",
  },
  {
    id: 7,
    bookImage: "/assets/Books/Asset5.png",
    authorName: "David Harris",
    description:
      "David Harris offers a riveting account of historical events that shaped the modern world.",
    moreInfo: "+ MORE ABOUT DAVID HARRIS",
    bookTitle: "Turning Points",
    fullDescription:
      "Turning Points is a detailed chronicle of pivotal moments in history that have had lasting impacts on society. David Harris's meticulous research and engaging narrative style make this a must-read for history enthusiasts.",
    isbn: "9785678912345",
    publishedDate: "05/03/2016",
    pages: 320,
    wordsCount: 85000,
    size: "230x150mm",
    imprint: "History Chronicles",
    bookGenre: "History",
  },
  {
    id: 8,
    bookImage: "/assets/Books/Asset6.png",
    authorName: "Sophie Lee",
    description:
      "Sophie Lee's collection of short stories captures the complexities of everyday life.",
    moreInfo: "+ MORE ABOUT SOPHIE LEE",
    bookTitle: "Moments of Clarity",
    fullDescription:
      "Moments of Clarity is a collection of short stories that reflect on the small yet significant moments that define our lives. Sophie Lee's keen observations and nuanced storytelling make this an evocative read.",
    isbn: "9781230987654",
    publishedDate: "22/09/2019",
    pages: 200,
    wordsCount: 60000,
    size: "205x130mm",
    imprint: "Storytellers Press",
    bookGenre: "Fiction",
  },
  {
    id: 9,
    bookImage: "/assets/Books/Asset2.png",
    authorName: "Mark Thompson",
    description:
      "Mark Thompson delves into the intricacies of human relationships in his latest novel.",
    moreInfo: "+ MORE ABOUT MARK THOMPSON",
    bookTitle: "Interwoven Lives",
    fullDescription:
      "Interwoven Lives explores the connections and disconnections among a group of individuals as they navigate life's challenges. Mark Thompson's insightful characterizations and compelling plot make this a deeply affecting read.",
    isbn: "9789876543210",
    publishedDate: "17/11/2017",
    pages: 310,
    wordsCount: 78000,
    size: "220x140mm",
    imprint: "Life Stories Publishing",
    bookGenre: "Fiction",
  },
  {
    id: 10,
    bookImage: "/assets/Books/Asset3.png",
    authorName: "Laura Martinez",
    description:
      "Laura Martinez's latest book offers a profound reflection on personal growth and self-discovery.",
    moreInfo: "+ MORE ABOUT LAURA MARTINEZ",
    bookTitle: "Journey Within",
    fullDescription:
      "Journey Within is an introspective journey that delves into themes of self-discovery and personal growth. Laura Martinez's insightful prose and relatable experiences make this a transformative read.",
    isbn: "9786543210987",
    publishedDate: "20/06/2020",
    pages: 270,
    wordsCount: 70000,
    size: "210x135mm",
    imprint: "Inspire Press",
    bookGenre: "Self-Help",
  },
];
